//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.29 at 07:33:35 PM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://courwebservice.sn/demo-ws", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sn.courwebservice.demo_ws;
